name: Deployment

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    id-token: write
    contents: read
    packages: write

concurrency:
    group: deploy
    cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: buildx
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: build
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/creatorsgarten/oknize
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: publish
        uses: deploys-app/deploys-action@v1
        with:
          project: ${{ secrets.DEPLOYS_NAME }}
          location: gke.cluster-rcf2
          name: oknize
          image: ghcr.io/creatorsgarten/oknize
          minReplicas: 1
          maxReplicas: 1
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
